platform :ios, '7.0'

target "OperationCenter", :exclusive => true do
  pod "EEEInjector"
  # pod "EEEOperationCenter", :path => "../"
end

target "OperationCenterTests", :exclusive => true do
  pod "Kiwi/XCTest"
end
