platform :ios, '7.0'

target "OperationCenter", :exclusive => true do
  pod "EEEInjector", '~> 1.0'
  # pod "EEEInjector", :path => "../../EEEInjector"
end

target "OperationCenterTests", :exclusive => true do
  pod "Kiwi/XCTest"
end
